<script lang="ts">
	import { onMount } from 'svelte';
	import { KleriButton } from '$lib';
	import { getHighlighter } from '$lib/utils/highlighter';

	interface Props {
		component: string;
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		props: Record<string, any>;
	}

	let { component, props }: Props = $props();

	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	function formatValue(value: any, indent = 2): string {
		if (typeof value === 'boolean') return `{${value}}`;
		if (typeof value === 'number') return `{${value}}`;
		if (typeof value === 'string') return `"${value}"`;
		if (Array.isArray(value)) {
			if (value.length === 0) return `{[]}`;
			const innerIndent = ' '.repeat(indent + 2);
			const items = value.map((v) => `${innerIndent}${formatValue(v, indent + 2)}`).join(',\n');
			return `{[\n${items}\n${' '.repeat(indent)}]}`;
		}
		if (typeof value === 'object' && value !== null) {
			const entries = Object.entries(value);
			if (entries.length === 0) return `{{}}`;
			const innerIndent = ' '.repeat(indent + 2);
			const props = entries
				.map(([k, v]) => `${innerIndent}${k}: ${formatValue(v, indent + 2)}`)
				.join(',\n');
			return `{{\n${props}\n${' '.repeat(indent)}}}`;
		}
		return String(value);
	}

	let code = $derived.by(() => {
		const entries = Object.entries(props).filter(([key]) => key !== 'children');
		const propLines = entries.map(([key, value]) => `  ${key}=${formatValue(value)}`);

		if (props.children) {
			return `<${component}${propLines.length > 0 ? '\n' + propLines.join('\n') + '\n' : ''}>
  ${props.children}
</${component}>`;
		}

		return `<${component}${propLines.length > 0 ? '\n' + propLines.join('\n') + '\n' : ''}/>`;
	});

	let copied = $state(false);
	let highlighter = $state<Awaited<ReturnType<typeof getHighlighter>> | null>(null);
	let highlightedHtml = $state('');

	onMount(async () => {
		highlighter = await getHighlighter();
		highlightedHtml = highlighter.codeToHtml(code, {
			lang: 'tsx',
			themes: { light: 'kleri-light', dark: 'kleri-dark' }
		});
	});

	$effect(() => {
		if (highlighter) {
			highlightedHtml = highlighter.codeToHtml(code, {
				lang: 'tsx',
				themes: { light: 'kleri-light', dark: 'kleri-dark' }
			});
		}
	});

	function copyCode() {
		navigator.clipboard.writeText(code);
		copied = true;
	}
</script>

<div class="overflow-hidden rounded-lg border-2 border-border bg-card">
	<div class="flex items-center justify-between border-b border-border/50 bg-muted/30 px-4 py-2">
		<span class="font-spacemono text-xs text-foreground">Usage</span>
		<KleriButton
			class="w-auto px-3 py-1 text-xs"
			showSuccess={copied}
			successMessage="Copied!"
			onSuccessComplete={() => (copied = false)}
			onclick={copyCode}
		>
			Copy
		</KleriButton>
	</div>

	<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
	<div role="region" aria-label={`${component} usage example`} tabindex="0" class="overflow-x-auto">
		{#if highlightedHtml}
			<!-- eslint-disable-next-line svelte/no-at-html-tags -- HTML generated by shiki syntax highlighter (trusted source, no user input) -->
			{@html highlightedHtml}
		{:else}
			<pre class="p-4 font-spacemono text-sm text-foreground"><code>{code}</code></pre>
		{/if}
	</div>
</div>
