<script lang="ts">
	import { onMount } from 'svelte';
	import { Check, Copy } from '@lucide/svelte';
	import KleriUtilityButton from '$lib/button/KleriUtilityButton/KleriUtilityButton.svelte';
	import { getHighlighter } from '$lib/utils/highlighter';
	import { formatSnippet } from './snippet.js';

	interface Props {
		/** Component name, used in the tag and the import line. */
		component: string;
		/** Prop values to print. `children` (a string) becomes the tag's content. */
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		props: Record<string, any>;
		/** Values printed as bare identifiers (icons, components), e.g. `Sun` → `Sun`. */
		symbols?: Map<unknown, string>;
		/** The component's defaults. Props equal to their default are left out. */
		defaults?: Record<string, unknown>;
		/** Props written as `bind:name`, backed by a `$state` declaration. */
		bindings?: string[];
		/** Module the component is imported from. @default '@kleri/ui' */
		from?: string;
		/** Other names imported from `from`, e.g. a group's item component. */
		importNames?: string[];
		/** Extra import lines, e.g. for the icons named in `symbols`. */
		imports?: string[];
		/** Replaces the generated snippet, for usage the generator can't express. */
		code?: string;
	}

	let {
		component,
		props,
		symbols,
		defaults,
		bindings,
		from = '@kleri/ui',
		importNames,
		imports,
		code: codeOverride
	}: Props = $props();

	let code = $derived(
		codeOverride ??
			formatSnippet({
				component,
				props,
				symbols,
				defaults,
				bindings,
				from,
				importNames,
				imports
			})
	);

	let copied = $state(false);
	let copyTimer: ReturnType<typeof setTimeout> | undefined;
	let highlighter = $state<Awaited<ReturnType<typeof getHighlighter>> | null>(null);

	onMount(() => {
		getHighlighter()
			.then((loaded) => (highlighter = loaded))
			.catch((error) => {
				// The plain <pre> fallback below stays on screen.
				console.error('Failed to load the syntax highlighter:', error);
			});
		return () => clearTimeout(copyTimer);
	});

	let highlightedHtml = $derived(
		highlighter?.codeToHtml(code, {
			lang: 'svelte',
			themes: { light: 'kleri-light', dark: 'kleri-dark' }
		}) ?? ''
	);

	async function copyCode() {
		try {
			await navigator.clipboard.writeText(code);
			copied = true;
			clearTimeout(copyTimer);
			copyTimer = setTimeout(() => (copied = false), 2000);
		} catch (error) {
			// Clipboard access is denied outside a secure context; don't claim success.
			console.error('Failed to copy to the clipboard:', error);
		}
	}
</script>

<div class="overflow-hidden rounded-kleri border border-border/50 bg-card">
	<div
		class="flex items-center justify-between border-b border-border/30 bg-muted/30 py-1.5 ps-4 pe-2"
	>
		<span class="font-spacemono text-xs text-foreground">Usage</span>
		<KleriUtilityButton
			size="xs"
			variant="ghost"
			class="inline-flex flex-row flex-nowrap items-center gap-1.5"
			onclick={copyCode}
		>
			{#if copied}
				<Check class="size-3.5 text-brand" aria-hidden="true" />
				Copied
			{:else}
				<Copy class="size-3.5" aria-hidden="true" />
				Copy
			{/if}
		</KleriUtilityButton>
		<span class="sr-only" aria-live="polite">{copied ? 'Code copied to the clipboard' : ''}</span>
	</div>

	<!-- svelte-ignore a11y_no_noninteractive_tabindex -->
	<div role="region" aria-label={`${component} usage example`} tabindex="0" class="overflow-x-auto">
		{#if highlightedHtml}
			<!-- eslint-disable-next-line svelte/no-at-html-tags -- HTML generated by shiki syntax highlighter (trusted source, no user input) -->
			{@html highlightedHtml}
		{:else}
			<pre class="p-4 font-spacemono text-sm text-foreground"><code>{code}</code></pre>
		{/if}
	</div>
</div>
